package com.example.maintenance_app

import android.content.Context
import android.graphics.Bitmap
import org.tensorflow.lite.DataType
import org.tensorflow.lite.Interpreter
import org.tensorflow.lite.support.common.ops.NormalizeOp
import org.tensorflow.lite.support.image.ImageProcessor
import org.tensorflow.lite.support.image.TensorImage
import org.tensorflow.lite.support.image.ops.ResizeOp
import java.io.FileInputStream
import java.nio.channels.FileChannel

class YoloDetector(context: Context, modelPath: String) {

    private var interpreter: Interpreter
    private val imageProcessor: ImageProcessor

    init {
        // 1. MODEL LOADING
        // Fetch the .tflite file from the "assets" folder
        val assetFileDescriptor = context.assets.openFd(modelPath)
        val fileInputStream = FileInputStream(assetFileDescriptor.fileDescriptor)
        val fileChannel = fileInputStream.channel
        val modelBuffer = fileChannel.map(
            FileChannel.MapMode.READ_ONLY,
            assetFileDescriptor.startOffset,
            assetFileDescriptor.declaredLength
        )

        // 2. TFLITE ENGINE INITIALIZATION
        val options = Interpreter.Options().apply {
            numThreads = 4 // Use 4 CPU threads for smoother performance
        }
        interpreter = Interpreter(modelBuffer, options)

        // 3. PRE-PROCESSING PIPELINE
        // YOLOv8 requires a 640x640 square image with pixel values normalized between 0.0 and 1.0
        imageProcessor = ImageProcessor.Builder()
            .add(ResizeOp(640, 640, ResizeOp.ResizeMethod.BILINEAR))
            .add(NormalizeOp(0f, 255f)) // Divides each pixel value by 255
            .build()
    }

    fun detect(bitmap: Bitmap) {
        // --- STEP A: IMAGE PREPARATION ---
        var tensorImage = TensorImage(DataType.FLOAT32)
        tensorImage.load(bitmap)
        tensorImage = imageProcessor.process(tensorImage) // Resizes and normalizes

        // --- STEP B: OUTPUT PREPARATION ---
        // Output Type: TensorSpec(shape=(1, 9, 8400))
        // 9 corresponds to: 4 bounding box coordinates + 5 object classes (e.g., clean brushes...)
        // 8400 is the number of raw bounding box proposals generated by YOLOv8
        val outputArray = Array(1) { Array(9) { FloatArray(8400) } }

        // --- STEP C: INFERENCE ---
        // Feed the image to the model; it populates "outputArray" with its predictions
        interpreter.run(tensorImage.buffer, outputArray)

        // TODO: NMS (Non-Maximum Suppression) algorithm goes here!
    }

    // Essential function to prevent memory leaks when exiting the camera view
    fun close() {
        interpreter.close()
    }
}