package com.example.maintenance_app

import android.content.Context
import android.graphics.Bitmap
import org.tensorflow.lite.DataType
import org.tensorflow.lite.Interpreter
import org.tensorflow.lite.support.common.ops.NormalizeOp
import org.tensorflow.lite.support.image.ImageProcessor
import org.tensorflow.lite.support.image.TensorImage
import org.tensorflow.lite.support.image.ops.ResizeOp
import timber.log.Timber
import java.io.FileInputStream
import java.nio.channels.FileChannel

// Data class to cleanly store a bounding box
data class Detection(
    val left: Float,
    val top: Float,
    val right: Float,
    val bottom: Float,
    val score: Float,
    val classIndex: Int
)

class YoloDetector(context: Context, modelPath: String) {

    private var interpreter: Interpreter
    private val imageProcessor: ImageProcessor

    init {
        // 1. MODEL LOADING
        // Fetch the .tflite file from the "assets" folder
        val assetFileDescriptor = context.assets.openFd(modelPath)
        val fileInputStream = FileInputStream(assetFileDescriptor.fileDescriptor)
        val fileChannel = fileInputStream.channel
        val modelBuffer = fileChannel.map(
            FileChannel.MapMode.READ_ONLY,
            assetFileDescriptor.startOffset,
            assetFileDescriptor.declaredLength
        )

        // 2. TFLITE ENGINE INITIALIZATION
        val options = Interpreter.Options().apply {
            numThreads = 4 // Use 4 CPU threads for smoother performance
        }
        interpreter = Interpreter(modelBuffer, options)

        // 3. PRE-PROCESSING PIPELINE
        // YOLOv8 requires a 640x640 square image with pixel values normalized between 0.0 and 1.0
        imageProcessor = ImageProcessor.Builder()
            .add(ResizeOp(640, 640, ResizeOp.ResizeMethod.BILINEAR))
            .add(NormalizeOp(0f, 255f)) // Divides each pixel value by 255
            .build()
    }

    fun detect(bitmap: Bitmap): List<Detection> {
        // --- STEP A: IMAGE PREPARATION ---
        var tensorImage = TensorImage(DataType.FLOAT32)
        tensorImage.load(bitmap)
        tensorImage = imageProcessor.process(tensorImage)

        // --- STEP B: OUTPUT PREPARATION ---
        // Output Type: TensorSpec(shape=(1, 9, 8400))
        // 9 corresponds to: 4 bounding box coordinates + 5 object classes (e.g., clean brushes...)
        // 8400 is the number of raw bounding box proposals generated by YOLOv8
        val outputArray = Array(1) { Array(9) { FloatArray(8400) } }

        // --- STEP C: INFERENCE ---
        // Feed the image to the model; it populates "outputArray" with its predictions
        interpreter.run(tensorImage.buffer, outputArray)

        // --- STEP D: POST-PROCESSING AND NMS ---

        // 1. Filtering parameters (adjust according to your needs)
        val confidenceThreshold = 0.4f // The model must be at least 40% confident
        val iouThreshold = 0.5f // If two boxes overlap by more than 50%, we only keep one

        // The output dimensions are [1][9][8400]
        // We logically transpose it to read column by column (the 8400 predictions)
        val numPredictions = 8400
        val numElements = 9 // 4 (x, y, w, h) + 5 classes

        val rawPredictions = outputArray[0]
        val validDetections = mutableListOf<Detection>()

        // 2. Filtering by confidence score
        for (i in 0 until numPredictions) {
            // Find the class with the highest score for this box
            var maxScore = -1f
            var classIndex = -1

            // Class scores start at index 4
            for (c in 4 until numElements) {
                val score = rawPredictions[c][i]
                if (score > maxScore) {
                    maxScore = score
                    classIndex = c - 4
                }
            }

            // If the best score exceeds our threshold, we keep this box
            if (maxScore >= confidenceThreshold) {
                // YOLOv8 outputs: center_x, center_y, width, height
                val cx = rawPredictions[0][i]
                val cy = rawPredictions[1][i]
                val w = rawPredictions[2][i]
                val h = rawPredictions[3][i]

                // Convert to standard format (left, top, right, bottom)
                val left = cx - w / 2
                val top = cy - h / 2
                val right = cx + w / 2
                val bottom = cy + h / 2

                validDetections.add(
                    Detection(
                        left = left,
                        top = top,
                        right = right,
                        bottom = bottom,
                        score = maxScore,
                        classIndex = classIndex
                    )
                )
            }
        }

        // 3. NMS (Non-Maximum Suppression) Algorithm
        // Sort detections by descending score
        validDetections.sortByDescending { it.score }

        val finalDetections = mutableListOf<Detection>()
        val active = BooleanArray(validDetections.size) { true }

        for (i in validDetections.indices) {
            if (!active[i]) continue

            val detA = validDetections[i]
            finalDetections.add(detA)

            // Compare with all subsequent boxes (lower confidence)
            for (j in i + 1 until validDetections.size) {
                if (!active[j]) continue

                val detB = validDetections[j]

                // If it's the same class, we check the overlap (IoU)
                if (detA.classIndex == detB.classIndex) {
                    if (calculateIoU(detA, detB) > iouThreshold) {
                        active[j] = false // We remove box B as it overlaps too much with box A
                    }
                }
            }
        }

        // 4. (Optional for now) Print results to the console for verification
        finalDetections.forEach {
            Timber.tag("YOLO_TEST").d("Found class ${it.classIndex} with confidence ${it.score} at coords: ${it.left}, ${it.top}")
        }

        return finalDetections
    }

    // Mathematical function to calculate the overlap between two boxes (IoU threshold)
    private fun calculateIoU(a: Detection, b: Detection): Float {
        val x1 = maxOf(a.left, b.left)
        val y1 = maxOf(a.top, b.top)
        val x2 = minOf(a.right, b.right)
        val y2 = minOf(a.bottom, b.bottom)

        val intersectionArea = maxOf(0f, x2 - x1) * maxOf(0f, y2 - y1)
        val boxAArea = (a.right - a.left) * (a.bottom - a.top)
        val boxBArea = (b.right - b.left) * (b.bottom - b.top)

        return intersectionArea / (boxAArea + boxBArea - intersectionArea)
    }

    // Essential function to prevent memory leaks when exiting the camera view
    fun close() {
        interpreter.close()
    }
}